%YAML:1.0
ar_sys_boards:
   - { name:"map", path:"boardconfig_122.yml", marker_size:0.2 }
   - { name:"odom", path:"boardconfig_152.yml", marker_size:0.2 }
   - { name:"raw_board_3", path:"boardconfig_344.yml", marker_size:0.2 }
   - { name:"raw_board_4", path:"boardconfig_591.yml", marker_size:0.2 }
