%YAML:1.0
ar_sys_boards:
   - { name:"raw_origin", path:"origin.yml", marker_size:0.25 }
   - { name:"raw_center", path:"center.yml", marker_size:0.25 }
   - { name:"raw_1", path:"boardconfig_122.yml", marker_size:0.2 }
   - { name:"raw_2", path:"boardconfig_152.yml", marker_size:0.2 }
   - { name:"raw_3", path:"boardconfig_344.yml", marker_size:0.2 }
   - { name:"raw_4", path:"boardconfig_591.yml", marker_size:0.2 }
